version: "3.5"
 
services:
  api:
    build: .
    env_file: 
      - envs/database.env
      - envs/authentication.env
      - envs/message_service.env
      - envs/message_listener.env
    image: api_image
<<<<<<< HEAD
    
    command: python3 app.py
=======
    command: python3 main.py
>>>>>>> 532114a... Added listener service to update results incoming from model apis via message service
    ports:
      - 3000:8000 
    networks:
      - nats-network
      - mongo-network
      
  mongo:
    image: mongo
    env_file:
      - envs/mongo.env
    restart: always
    logging:
      driver: "none"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    env_file:
      - envs/mongo.env
    restart: always
    logging:
      driver: "none"
    ports:
      - 8081:8081
    networks:
      - mongo-network

  nats-server:
    image: nats:2.8.4
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge
    name: nats-bridge

  mongo-network:
    name: mongo-bridge


  
