version: "3"
 
services:
  api:
    build: .
    env_file: 
      - envs/database.env
      - envs/authentication.env
    image: api_image
    command: python3 app.py
    ports:
      - 3000:8000 
      
  mongo:
    image: mongo
    env_file:
      - envs/mongo.env
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - envs/mongo.env