version: "3.5"
 
services:
  api:
    build: .
    restart: always
    env_file: 
      - envs/database.env
      - envs/authentication.env
      - envs/message_service.env
      - envs/message_listener.env
      - envs/simple_storage.env
    image: api_image
    command: python3 main.py
    ports:
      - 3000:8000 
    networks:
      - nats-network
      - mongo-network
      - minio-network
      
  mongo:
    image: mongo
    env_file:
      - envs/mongo.env
    restart: always
    logging:
      driver: "none"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    env_file:
      - envs/mongo.env
    restart: always
    logging:
      driver: "none"
    ports:
      - 8081:8081
    networks:
      - mongo-network

  nats-server:
    image: nats:2.8.4
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - nats-network

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ':9001' --address ':9000'
    volumes:
      - minio_data:/data
    env_file:
      - envs/minio.env
    networks:
      - minio-network


networks:
  nats-network:
    driver: bridge
    name: nats-bridge

  mongo-network:
    name: mongo-bridge

  minio-network:
    driver: bridge
    name: minio-bridge

volumes:
  minio_data:

  
